---
- name: Identify Pi
  debug: var=ansible_facts

- name: Set IP Information
  set_fact:
      myPiIP: "{{ ansible_facts['eth0']['ipv4']['address']}}"
      myPiName: "{{ ansible_facts['nodename'] }}"

- name: "{{ Ansible_Project }} | RED"
  shell: blinkstick --index 0 RED

- name: "{{ Ansible_Project }} | RED"
  shell: blinkstick --index 1 RED

- name: "Announcement"
  shell: >
      cmd: python3 rangerPi.py 'Set Lighting to Tactical  ' 'en-us'
      chdir: myDev/gTTs
  when: "myPiIP == '192.168.1.59'"

- name: Tactical Beeps
  shell: >
      cmd: mpg123 /home/pi/myDev/gTTs/sounds/tactical_beep_sequence.mp3
  when: "myPiIP == '192.168.1.59'"

- name: "Displaying Kubernetes Cluster POD"
  shell: >
      cmd: python3 rangerPi.py
      'Start Servers for Ansible Tower and Jenkins' 'en-us'
      chdir: myDev/gTTs
  when: "myPiIP == '192.168.1.59'"

- name: Start Servers
  shell:
      cmd: mpg123 /home/pi/myDev/gTTs/sounds/tos_com_beep_1.mp3
  when: "myPiIP == '192.168.1.59'"

- name: "Start Scanning for Dynamic Inventory Elements"
  shell:
      cmd: python3 rangerPi.py 'Begin Deep Inventory Scans' 'en-us'
      chdir: myDev/gTTs
  when: "myPiIP == '192.168.1.59'"

- name: Start Servers
  shell:
      cmd: mpg123 /home/pi/myDev/gTTs/sounds/tos_tricorder_scan.mp3
  when: "myPiIP == '192.168.1.59'"

- name: Scanning
  shell:
      cmd: mpg123 /home/pi/myDev/gTTs/sounds/tos_scanner.mp3
  when: "myPiIP == '192.168.1.59'"

- name: Scanning
  shell:
      cmd: mpg123 /home/pi/myDev/gTTs/sounds/tos_working.mp3
  when: "myPiIP == '192.168.1.59'"

- name: Scanning
  shell:
      cmd: python3 rangerPi.py 'Wow thats an old computer' 'en'
  when: "myPiIP == '192.168.1.59'"
