---
- hosts: localhost
  gather_facts: no
  connection: local

  vars:
    should_fail_via_fail: false
    should_fail_via_assert: false
    should_fail_via_complex_assert: false

  tasks:
    - name: Fail if the conditions warrant a failure
      fail:
        msg: "There was an epic failure"
      when: should_fail_via_fail
    - name: Hard Stop of playbook if an assertion isn't validated
      assert:
        that: "should_fail_via_assert !=true"
    - name: Assertions can have contain conditions
      assert:
        that:
          - should_fail_via_fail !=true
          - should_fail_via_assert !=true
          - should_fail_via_complex_assert !=true

    - name: Register the output of the uptime command
      command: uptime
      register: system_uptime
    - name: Print the registered output of the 'uptime command'
      debug:
        var: system_uptime.stdout
    - name: Print a message if a command resulted in a change
      debug:
        msg: "Command Resulted in a Change"
      when: system_uptime is changed

- hosts: launched
  connection: ssh
  gather_facts: no
  become: true

  roles:
# - tactical
# - python3
# - apache
# - defcon
# - pi-rollcall
# - tactical
# - chaos
