---
- hosts: rangerPi
  gather_facts: yes
  connection: local
  become: true
  become_method: sudo
  #vars:
  #  should_fail_via_fail: false
  #  should_fail_via_assert: false
  #  should_fail_via_complex_assert: false

  #tasks:
  #  - name: Fail if the conditions warrant a failure
  #    fail:
  #      msg: "There was an epic failure"
  #    when: should_fail_via_fail
  #  - name: Hard Stop of playbook if an assertion isn't validated
  #    assert:
  #      that: "should_fail_via_assert !=true"
  #  - name: Assertions can have contain conditions
  #    assert:
  #      that:
  #        - should_fail_via_fail !=true
  #        - should_fail_via_assert !=true
  #        - should_fail_via_complex_assert !=true

    # - name: Register Device Temperature for each Device
    #   register: system_temp
    #   command: 'vcgencmd measure_temp'

    # - name: Register the output of the uptime command
    #   command: uptime
    #   register: system_uptime

    # - name: Print the registered output of the System Temperture
    #   debug:
    #     var: system_temp.stdout
    #   when: system_temp is changed

    # - name: Print a message if a Temperature Changed
    #   debug:
    #     msg: "{{ ansible_facts['nodename'] }}  {{ system_temp.stdout }}"
  roles:
  - samba #- conky
#  - python3
#  - vcode
# - pi-os
#  - tempcheck
#  - tactical
# - vcode
#  - blinkstick
# - conky
# - python3
# - apache
#  - defcon
#  - pi-rollcall
#  - tactical
#  - chaos
# - virtualbox