---
# tasks file for defcon
- name: Identify Pi
  debug: var=ansible_facts

- name: "Set Color"
  command: blinkstick --morph --set-color=BLUE

- name: "Set Color"
  command: blinkstick --index 1 BLUE
