---
- name: "{{ Ansible_Project }} | Texas Welcome"
  shell:
    cmd: python3 rangerPi.py 'Where yall from ?' 'en-us'
    chdir: myDev/gTTs
  when: "myPiIP == '192.168.1.59'"

- name: "{{ Ansible_Project }} | Howdy"
  shell:
    cmd: python3 rangerPi.py 'Why Texas Maam !' 'de'
    chdir: myDev/gTTs
  when: "myPiIP == '192.168.1.59'"

- name: "{{ Ansible_Project }} | OMG"
  shell:
    cmd: python3 rangerPi.py 'Texas !! Well, only two things from Texas!' 'en-us'
    chdir: myDev/gTTs
  when: "myPiIP == '192.168.1.59'"

- name: "{{ Ansible_Project }} | OMG"
  shell:
    cmd: python3 rangerPi.py 'Ok you PODS, Lets take a quick roll call' 'en-uk'
    chdir: myDev/gTTs
  when: "myPiIP == '192.168.1.59'"
