---
- name: Install base packages locales
  apt:
    name: locales
    state: present
- name: Install base build-essential
  apt:
    name: build-essential
    state: present
- name: Install base packages acl
  apt:
    name: acl
    state: present
- name: Install base packages ntp
  apt:
    name: ntp
    state: present
- name: Install base packages htop
  apt:
    name: htop
    state: present
- name: Install base packages git
  apt:
    name: git
    state: present

- name: Install base packages supervisor
  apt:
    name: supervisor
    state: present

- name: Install base packages python
  apt:
    name: python
    state: present

- name: Install base packages python3-pip
  apt:
    name: python3-pip
    state: present

- name: Install base packages python-apt
  apt:
    name: python-apt
    state: present

- name: Install venv
  apt:
    name: python3-venv
    state: present

- name: Install Setup Tools
  apt:
    name: python-setuptools
    state: present

- name: Install Setup Wheel
  apt:
    name: python3-wheel
    state: present

- name: Install Python Pip
  apt:
    name: python3-pip
    state: present

- name: Check the version of python 3.x exists
  stat:
    path: /usr/local/bin/python3.8
  tags: python
  register: python_result

- name: Update apt-cache check for results
  apt:
    update_cache: yes
  tags: python
  when: python_result.stat.exists == False
