---
- name: Identify Pi
  debug: var=ansible_facts

- name: Set IP Information
  set_fact:
      myPiIP: "{{ ansible_facts['eth0']['ipv4']['address']}}"
      myPiName: "{{ ansible_facts['nodename'] }}"

- name: "{{ Ansible_Project }}"
  command: "bash who.sh"
  when: "myPiIP == '192.168.1.50'"

- name: "{{ Ansible_Project }}"
  shell:
      cmd: >
        ssh 192.168.1.59 python3
        rangerPi.py 'Pod \0.\Blue.' 'ro'
  when: "myPiIP == '192.168.1.50'"

- name: "{{ Ansible_Project }} "
  command: "bash who.sh"
  when: "myPiIP == '192.168.1.51'"

- name: "{{ Ansible_Project }} "
  shell:
      cmd: >
        ssh 192.168.1.59 python3
        rangerPi.py 'Pod\1.\Orange' 'en-uk'
  when: "myPiIP == '192.168.1.51'"

- name: "{{ Ansible_Project }} "
  command: "bash who.sh"
  when: "myPiIP == '192.168.1.52'"

- name: "{{ Ansible_Project }} "
  shell:
      cmd: >
        ssh 192.168.1.59 python3
        rangerPi.py 'Pod\2.\Red,\present' 'en'
  when: "myPiIP == '192.168.1.52'"

- name: "{{ Ansible_Project }} "
  command: "bash who.sh"
  when: "myPiIP == '192.168.1.53'"

- name: "{{ Ansible_Project }} "
  shell:
      cmd: >
        ssh 192.168.1.59 python3
        rangerPi.py 'Pod\three\Green,\Here' 'de'
  when: "myPiIP == '192.168.1.53'"

- name: "{{ Ansible_Project }} "
  command: "bash who.sh"
  when: "myPiIP == '192.168.1.54'"

- name: "{{ Ansible_Project }} "
  shell:
      cmd: >
        ssh 192.168.1.59 python3
        rangerPi.py 'Pod\4,\Purple.\Yo' 'en-nz'
  when: "myPiIP == '192.168.1.54'"

- name: "{{ Ansible_Project }} "
  command: "bash who.sh"
  when: "myPiIP == '192.168.1.55'"

- name: "{{ Ansible_Project }} "
  shell: >
      cmd: ssh 192.168.1.59 python3
        rangerPi.py 'Pod\five\White\Here.' 'pl'
  when: "myPiIP == '192.168.1.55'"


- name: "{{ Ansible_Project }} "
  command: "bash who.sh"
  when: "myPiIP == '192.168.1.56'"

- name: "{{ Ansible_Project }} "
  shell:
      cmd: >
        ssh 192.168.1.59
        python3 rangerPi.py
        'Pod\six\Baby\Blue.Here.' 'fr'
  when: "myPiIP == '192.168.1.56'"

- name: "{{ Ansible_Project }}"
  command: "bash who.sh"
  when: "myPiIP == '192.168.1.57'"

- name: "{{ Ansible_Project }}"
  shell:
      cmd: >
        ssh 192.168.1.59 python3 rangerPi.py
        'Pod\ Seven\Peechie\Here.\I\think\its\ a\color'
        'es-es'
  when: "myPiIP == '192.168.1.57'"

- name: "{{ Ansible_Project }} "
  command: "bash who.sh"
  when: "myPiIP == '192.168.1.58'"

- name: "{{ Ansible_Project }} "
  shell:
      cmd: >
       ssh 192.168.1.59 python3
          rangerPi.py 'Pod\eight.\Light\Green,\here' 'cs'
  when: "myPiIP == '192.168.1.58'"

- name: "{{ Ansible_Project }} "
  command: "bash who.sh"
  when: "myPiIP == '192.168.1.59'"

- name: "{{ Ansible_Project }} | {{ myPiName }}"
  shell:
      cmd: python3 rangerPi.py 'Pod\nine,\Gold\here' 'it'
  when: "myPiIP == '192.168.1.59'"
