---
- name: "{{ Ansible_Project }} | Kube 0"
  shell:
    cmd: python3 rangerPi.py 'Kube 0 is here and ready' 'en'
    chdir: myDev/gTTs

- name: "{{ Ansible_Project }} | Kube 1"
  shell:
    cmd: python3 rangerPi.py 'Kube 1, Checking in. Whats for lunch, Im hungry.' 'fr'
    chdir: myDev/gTTs

- name: "{{ Ansible_Project }} | Kube 2"
  shell:
    cmd: python3 rangerPi.py 'Kube 2. I am here, what no sausage ?' 'jw'
    chdir: myDev/gTTs

- name: "{{ Ansible_Project }} | Kube 3"
  shell:
    cmd: python3 rangerPi.py 'Kube 3, Checking in. On site, on time and always under budget' 'en'
    chdir: myDev/gTTs

- name: "{{ Ansible_Project }} | Kube 4"
  shell:
    cmd: python3 rangerPi.py 'Kube 4. Just Checked in. Know what I mean ?' 'en-nz'
    chdir: myDev/gTTs

- name: "{{ Ansible_Project }} | Kube 5"
  shell:
    cmd: python3 rangerPi.py 'Kube 5. Oh, Im here. Packin and stackin' 'en'
    chdir: myDev/gTTs

- name: "{{ Ansible_Project }} | Kube 6"
  shell:
    cmd: python3 rangerPi.py 'Kube 6. Not today. Dont make me sing. I am prettier than your alexa. No ?' 'fr'
    chdir: myDev/gTTs


- name: "{{ Ansible_Project }} | Kube 7"
  shell:
    cmd: python3 rangerPi.py 'Kube 7. I am present. But not much more.' 'es-es'
    chdir: myDev/gTTs


- name: "{{ Ansible_Project }} | Kube 8"
  shell:
    cmd: python3 rangerPi.py 'Kube 8 is here. But not happy' 'en-uk'
    chdir: myDev/gTTs


- name: "{{ Ansible_Project }} | Kube 9"
  shell:
    cmd: python3 rangerPi.py 'Kube 9 is 5 by 5 and thats all you get out of me. Call frenchie, she will take your order' 'en'
    chdir: myDev/gTTs
