---
- name: Identify Pi
  debug: var=ansible_facts

- name: Set IP Information
  set_fact:
    myPiIP: "{{ ansible_facts['eth0']['ipv4']['address']}}"
    myPiName: "{{ ansible_facts['nodename'] }}"

- name: "{{ Ansible_Project }}"
  copy:
    src: /vars/scott.py
    dest: /myDev/blink/scott.py
    owner: pi
    mode: 0644
