---
- name: Identify Pi
  debug: var=ansible_facts

- name: Set IP Information
  set_fact:
    myPiIP: "{{ ansible_facts['wlan0']['ipv4']['address']}}"
    myPiName: "{{ ansible_facts['nodename'] }}"

- name: "{{ Ansible_Project }} | Blue"
  shell: blinkstick --index 0 BLUE

- name: "{{ Ansible_Project }} | Blue"
  shell: blinkstick --index 1 BLUE

- name: "Server Information | {{ myPiIP }} | {{ myPiName }}"
  debug: msg="{{ myPiIP }}"
