---
- hosts: localhost
  gather_facts: no
  connection: local
  -  SK - K9Fzm8Y6dznW+j9NMtOGlsDTG83k2quf9UjF/jK9
  -  AK - AKIATPN5V73GH7XYFEHI  tasks:
  - name: Get System Update
    command: uptime
    changed_when: false
    register: system_uptime

  - name: Print the registered output of the 'uptime command'
    debug:
      var: system_uptime.stdout
  - name: Print a message if a command resulted in a change
    debug:
      msg: "Command Resulted in a Change"
    when: system_uptime is changed
